### ISSUE TITLE
Logging array throws error for message.split at line 64

### ISSUE THREAD

**Issue by LordSyd** [sjinks/winston-mail-lite#52]
For my usecase I need to log an array of errors, that then gets split via a custom winston format. But if I do this, winston-mail-light throws the following error:

```
TypeError: message.split is not a function
      at Mail.log (C:\Users\daniel.kleissl\Documents\razzfazz\repos\Seqitracker-utils\seqitracker-util\node_modules\winston-mail-lite\lib\index.js:64:126)
      at Mail._write (C:\Users\daniel.kleissl\Documents\razzfazz\repos\Seqitracker-utils\seqitracker-util\node_modules\winston-transport\index.js:103:17)
      at doWrite (C:\Users\daniel.kleissl\Documents\razzfazz\repos\Seqitracker-utils\seqitracker-util\node_modules\readable-stream\lib\_stream_writable.js:409:139)  
      at writeOrBuffer (C:\Users\daniel.kleissl\Documents\razzfazz\repos\Seqitracker-utils\seqitracker-util\node_modules\readable-stream\lib\_stream_writable.js:398:5)
      at Mail.Writable.write (C:\Users\daniel.kleissl\Documents\razzfazz\repos\Seqitracker-utils\seqitracker-util\node_modules\readable-stream\lib\_stream_writable.js:307:11)
      at DerivedLogger.ondata (C:\Users\daniel.kleissl\Documents\razzfazz\repos\Seqitracker-utils\seqitracker-util\node_modules\readable-stream\lib\_stream_readable.js:681:20)
      at DerivedLogger.emit (events.js:327:22)
      at DerivedLogger.EventEmitter.emit (domain.js:467:12)
      at addChunk (C:\Users\daniel.kleissl\Documents\razzfazz\repos\Seqitracker-utils\seqitracker-util\node_modules\readable-stream\lib\_stream_readable.js:298:12)  
      at readableAddChunk (C:\Users\daniel.kleissl\Documents\razzfazz\repos\Seqitracker-utils\seqitracker-util\node_modules\readable-stream\lib\_stream_readable.js:280:11)
```

If I comment out the "message.split()" part of line 64 the mail gets send as expected and my format gets applied.

```javascript
messageOptions.subject = messageOptions.subject.replace(/{{\s*level\s*}}/g, level).replace(/{{\s*message\s*}}/g, /*message.split('\n')[0])*/;
```

Commenting this out or transforming the array into a string before logging certainly is an workaround, but only temporary.

**Comment by sjinks** [comment]
Hi, I have just published a version that fixes this issue, please take a look.

**Comment by LordSyd** [comment]
This looks good at the first glance. Will be able to try it out on Monday when I am back at work. Thanks for the swift reaction!
